import {
  DISTRIBUTION_PRECOMPILE_ABI,
  DISTRIBUTION_PRECOMPILE_ADDRESS,
} from '../precompiles';

export const DISTRIBUTION_PRECOMPILE_CONFIG = {
  address: DISTRIBUTION_PRECOMPILE_ADDRESS,
  abi: DISTRIBUTION_PRECOMPILE_ABI,
} as const;
